-- SIAP-DESA business schema
-- Application tables used by the Laravel modules.

CREATE TABLE IF NOT EXISTS citizens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, nik VARCHAR(16) NOT NULL UNIQUE, no_kk VARCHAR(16) NULL, name VARCHAR(150) NOT NULL,
 gender VARCHAR(20) NOT NULL, birth_place VARCHAR(80) NULL, birth_date DATE NULL, blood_type VARCHAR(5) NULL,
 religion VARCHAR(30) NULL, marital_status VARCHAR(30) NULL, occupation VARCHAR(80) NULL, education VARCHAR(50) NULL,
 address TEXT NULL, rt VARCHAR(5) NULL, rw VARCHAR(5) NULL, status VARCHAR(20) NOT NULL DEFAULT 'TETAP', notes TEXT NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL, KEY idx_citizen_village(village_id), KEY idx_citizen_kk(no_kk)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS families (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, no_kk VARCHAR(16) NOT NULL UNIQUE, head_name VARCHAR(150) NOT NULL, head_nik VARCHAR(16) NULL,
 address TEXT NULL, rt VARCHAR(5) NULL, rw VARCHAR(5) NULL, postal_code VARCHAR(10) NULL, issue_date DATE NULL, notes TEXT NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS family_members (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 family_id BIGINT UNSIGNED NOT NULL, citizen_id BIGINT UNSIGNED NOT NULL, relation_status VARCHAR(30) NOT NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_family_citizen(citizen_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employees (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, citizen_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, nip VARCHAR(30) NULL,
 position VARCHAR(100) NOT NULL, department VARCHAR(100) NULL, employment_status VARCHAR(40) NOT NULL,
 qr_token VARCHAR(120) NULL UNIQUE, join_date DATE NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employee_positions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 employee_id BIGINT UNSIGNED NOT NULL, position VARCHAR(100) NOT NULL, department VARCHAR(100) NULL,
 start_date DATE NULL, end_date DATE NULL, is_current TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attendance (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, employee_id BIGINT UNSIGNED NOT NULL, device_id CHAR(36) NULL, date DATE NOT NULL,
 time_in TIME NULL, time_out TIME NULL, status VARCHAR(30) NOT NULL, notes TEXT NULL, verified_by BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL,
 UNIQUE KEY uq_attendance_employee_date(employee_id,date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attendance_corrections (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 attendance_id BIGINT UNSIGNED NOT NULL, employee_id BIGINT UNSIGNED NOT NULL, requested_status VARCHAR(30) NULL,
 requested_time_in TIME NULL, requested_time_out TIME NULL, reason TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 approved_by BIGINT UNSIGNED NULL, approved_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS letter_types (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, template_view VARCHAR(190) NULL,
 number_format VARCHAR(255) NULL, fields_schema JSON NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS letters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, letter_type_id BIGINT UNSIGNED NOT NULL, citizen_id BIGINT UNSIGNED NULL,
 draft_number VARCHAR(100) NULL, letter_number VARCHAR(190) NULL, applicant_name VARCHAR(150) NOT NULL,
 applicant_nik VARCHAR(16) NULL, applicant_address TEXT NULL, purpose TEXT NULL, letter_data JSON NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', approved_by BIGINT UNSIGNED NULL, approved_at DATETIME NULL,
 issued_at DATE NULL, qr_verification_token VARCHAR(120) NULL UNIQUE, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS letter_dispositions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE,
 letter_id BIGINT UNSIGNED NOT NULL, from_user_id BIGINT UNSIGNED NULL, to_user_id BIGINT UNSIGNED NULL,
 instruction TEXT NULL, status VARCHAR(30) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS services (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, processing_days INT NOT NULL DEFAULT 1,
 requirements JSON NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS service_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, service_id BIGINT UNSIGNED NOT NULL, citizen_id BIGINT UNSIGNED NULL, request_number VARCHAR(100) NULL,
 request_data JSON NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', processed_at DATETIME NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS finance_accounts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, parent_id BIGINT UNSIGNED NULL, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL,
 type VARCHAR(30) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS finance_budgets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, account_id BIGINT UNSIGNED NOT NULL, fiscal_year INT NOT NULL,
 budgeted_amount DECIMAL(18,2) NOT NULL DEFAULT 0, budget_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
 realized_amount DECIMAL(18,2) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_budget(account_id,fiscal_year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS finance_transactions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, transaction_number VARCHAR(100) NULL UNIQUE, transaction_date DATE NOT NULL,
 account_id BIGINT UNSIGNED NOT NULL, type VARCHAR(30) NOT NULL, amount DECIMAL(18,2) NOT NULL,
 description TEXT NOT NULL, recipient_or_payer VARCHAR(150) NULL, payment_method VARCHAR(30) NULL,
 spj_number VARCHAR(80) NULL, status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', posted_by BIGINT UNSIGNED NULL, posted_at DATETIME NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS finance_transaction_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE,
 transaction_id BIGINT UNSIGNED NOT NULL, description TEXT NULL, quantity DECIMAL(12,2) NULL, unit_price DECIMAL(18,2) NULL,
 amount DECIMAL(18,2) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS finance_evidences (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 transaction_id BIGINT UNSIGNED NOT NULL, file_path VARCHAR(255) NULL, file_name VARCHAR(190) NULL, mime_type VARCHAR(100) NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS spj (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, transaction_id BIGINT UNSIGNED NOT NULL, spj_number VARCHAR(100) NOT NULL UNIQUE, date DATE NOT NULL,
 activity_name VARCHAR(200) NOT NULL, description TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
 prepared_by BIGINT UNSIGNED NULL, verified_by BIGINT UNSIGNED NULL, verified_at DATETIME NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS asset_categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, description TEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS assets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, category_id BIGINT UNSIGNED NOT NULL, asset_code VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL,
 acquisition_date DATE NULL, acquisition_source VARCHAR(80) NULL, acquisition_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
 condition VARCHAR(30) NOT NULL, location VARCHAR(150) NULL, custodian VARCHAR(100) NULL, status VARCHAR(30) NOT NULL DEFAULT 'AKTIF',
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS asset_mutations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 asset_id BIGINT UNSIGNED NOT NULL, mutation_type VARCHAR(50) NOT NULL, previous_value TEXT NULL, new_value TEXT NULL,
 date DATE NOT NULL, reason TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS aid_programs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 village_id CHAR(36) NULL, name VARCHAR(150) NOT NULL, year INT NOT NULL, code VARCHAR(50) NOT NULL,
 budget_per_recipient DECIMAL(18,2) NOT NULL DEFAULT 0, quota INT NOT NULL, source VARCHAR(150) NOT NULL,
 description TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS aid_recipients (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 aid_program_id BIGINT UNSIGNED NOT NULL, citizen_id BIGINT UNSIGNED NOT NULL, amount_received DECIMAL(18,2) NOT NULL DEFAULT 0,
 status VARCHAR(30) NOT NULL DEFAULT 'TERVERIFIKASI', distribution_date DATE NULL, distribution_reference VARCHAR(100) NULL,
 notes TEXT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_aid_recipient(aid_program_id,citizen_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_versions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, app_version VARCHAR(30) NOT NULL UNIQUE, schema_version INT NOT NULL,
 sync_protocol_version INT NOT NULL, remarks VARCHAR(255) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
